casc-v2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'homes#index'
  
  get 'admin' => 'homes#admin'
  get 'admin/:tab' => 'homes#admin'

  get 'casc_news', to: redirect("admin/news")
  get 'casc_news/new', to: 'casc_news#new', as: :new_casc_new
  get 'casc_news/:id', to: 'casc_news#show', as: :casc_new
  post 'casc_news', to: 'casc_news#create'
  get 'casc_news/:id/edit', to: 'casc_news#edit', as: :edit_casc_new
  patch 'casc_news/:id', to: 'casc_news#update'
  delete 'casc_news/:id', to: 'casc_news#destroy'



  resources :categories, only: [:index, :show, :edit, :update, :destroy, :new, :create]

  get 'challenges', to: redirect("admin/challenges")
  resources :challenges, only: [:show, :edit, :update, :destroy, :new, :create]

  resources :users
end

casc-v2/app/views/homes/partials/tabs/_categories.html.erb
<div class="flex-col h-full w-full">
  <div class="flex px-4" style="height: 6vh">
    <span class="my-auto">
      Total rows: <%= Category.all.count %>
    </span>
    <span class="ml-auto my-auto">
      <%= addButton("Add a category", new_category_path()) %>
    </span>
  </div>
  <div class="flex-col w-full overflow-scroll rounded-b-3xl" style="height: 74vh">
    <table class="w-full relative text-base text-left rtl:text-right">
      <thead class="green-text uppercase">
        <tr class="sticky top-0 highlight-bg-accent ">
          <th scope="col" class="px-4 py-3">
            <div class="flex items-center">
              title
            </div>
          </th>
          <th scope="col" class="px-4 py-3">
            <div class="flex items-center">
              creation date
            </div>
          </th>
          <th scope="col" colspan="2" class="px-4 py-3">
            <div class="flex items-center">
              description
            </div>
          </th>
          <th scope="col" class="px-4 py-3">
            <div class="flex items-center">
              edit
            </div>
          </th>
          <th scope="col" class="px-4 py-3">
            <div class="flex items-center">
              delete
            </div>
          </th>
        </tr>
      </thead>
      <tbody class="text-sm">
        <% Category.all.each do |categ| %>
          <tr title="<%= categ.description %>" class="odd:highlight-bg even:bg-regular border-b border-regular white-text hover:green-text hover:highlight-bg-accent cursor-pointer" onclick="window.location.href='<%= category_path(categ.id) %>'">
            <td class="px-4 py-1 whitespace-nowrap">
              <%= categ.title %>
            </td>
            <td class="px-4 py-1 whitespace-nowrap">
              <%= categ.updated_at.day %> <%= I18n.l(categ.updated_at, format: "%B")%> <%= categ.updated_at.year %>
            </td>
            <td colspan="2" class="px-4 py-1 whitespace-wrap">
              <%= categ.description.truncate(96, separator: ' ') %>
            </td>
            <td class="px-4 py-1 whitespace-wrap">
              <%= editButton("Edit this category", edit_category_path(categ)) %>
            </td>
            <td class="px-4 py-1 whitespace-wrap">
              <%= delButton("Delete a category", casc_news_path(categ), categ) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

casc-v2/app/views/homes/partials/tabs/_challenges.html.erb
<div class="flex-col h-full w-full">
  <div class="flex px-4" style="height: 6vh">
    <span class="my-auto">
      Total rows: <%= Challenge.all.count %>
    </span>
    <span class="ml-auto my-auto">
      <%= addButton("Add a challenge", new_challenge_path()) %>
    </span>
  </div>
  <div class="flex-col w-full overflow-scroll rounded-b-3xl" style="height: 74vh">
    <table class="w-full relative text-base text-left rtl:text-right">
      <thead class="green-text uppercase">
        <tr class="sticky top-0 highlight-bg-accent ">
          <th scope="col" class="px-4 py-3">
            <div class="flex items-center">
              title
            </div>
          </th>
          <th scope="col" class="px-4 py-3">
            <div class="flex items-center">
              creation date
            </div>
          </th>
          <th scope="col" colspan="2" class="px-4 py-3">
            <div class="flex items-center">
              description
            </div>
          </th>
          <th scope="col" class="px-4 py-3">
            <div class="flex items-center">
              edit
            </div>
          </th>
          <th scope="col" class="px-4 py-3">
            <div class="flex items-center">
              delete
            </div>
          </th>
        </tr>
      </thead>
      <tbody class="text-sm">
        <% Challenge.all.each do |chall| %>
          <tr title="<%= chall.description %>" class="odd:highlight-bg even:bg-regular border-b border-regular white-text hover:green-text hover:highlight-bg-accent cursor-pointer" onclick="window.location.href='<%= challenge_path(chall.id) %>'">
            <td class="px-4 py-1 whitespace-nowrap">
              <%= chall.title %>
            </td>
            <td class="px-4 py-1 whitespace-nowrap">
              <%= chall.updated_at.day %> <%= I18n.l(chall.updated_at, format: "%B")%> <%= chall.updated_at.year %>
            </td>
            <td colspan="2" class="px-4 py-1 whitespace-wrap">
              <%= chall.description.truncate(96, separator: ' ') %>
            </td>
            <td class="px-4 py-1 whitespace-wrap">
              <%= editButton("Edit this challenge", edit_challenge_path(chall)) %>
            </td>
            <td class="px-4 py-1 whitespace-wrap">
              <%= delButton("Delete a challenge", challenge_path(chall), chall) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

casc-v2/app/views/homes/partials/tabs/_news.html.erb
<div class="flex-col h-full w-full">
  <div class="flex py-auto px-4" style="height: 6vh">
    <span class="my-auto">
      Total rows: <%= CascNew.all.count %>
    </span>
    <span class="ml-auto my-auto">
      <%= addButton("Add a new", new_casc_new_path()) %>
    </span>
  </div>
  <div class="flex-col w-full overflow-scroll rounded-b-3xl" style="height: 74vh">
    <table class="w-full relative text-base text-left rtl:text-right">
      <thead class="green-text uppercase">
        <tr class="sticky top-0 highlight-bg-accent ">
          <th scope="col" class="px-6 py-3">
            <div class="flex items-center">
              type
            </div>
          </th>
          <th scope="col" class="px-4 py-3">
            <div class="flex items-center">
              title
            </div>
          </th>
          <th scope="col" class="px-4 py-3">
            <div class="flex items-center">
              date
            </div>
          </th>
          <th scope="col" class="px-4 py-3">
            <div class="flex items-center">
              content
            </div>
          </th>
          <th scope="col" class="px-4 py-3">
            <div class="flex items-center">
              author
            </div>
          </th>
          <th scope="col" class="px-4 py-3">
            <div class="flex items-center">
              edit
            </div>
          </th>
          <th scope="col" class="px-4 py-3">
            <div class="flex items-center">
              delete
            </div>
          </th>
        </tr>
      </thead>
      <tbody class="text-sm">
        <% CascNew.all.each do |new| %>
          <tr title="<%= new.content %>" class="odd:highlight-bg even:bg-regular border-b border-regular white-text hover:green-text hover:highlight-bg-accent cursor-pointer" onclick="window.location.href='<%= casc_new_path(new.id)%>'">
            <td class="px-4 py-1 whitespace-nowrap">
              <% case new.nType %>
              <% when "release" %>
                <img src='/assets/icons/release-w.png' class="w-6 h-6 mx-2 my-auto">
              <% when 'success' %>
                <img src='/assets/icons/cup-w.png' class="w-6 h-6 mx-2 my-auto">
              <% when 'event' %>
                <img src='/assets/icons/calendar-w.png' class="w-6 h-6 mx-2 my-auto">
              <% when 'test' %>
                <img src='/assets/icons/test-w.png' class="w-6 h-6 mx-2 my-auto">
              <% else %>
                <img src='/assets/icons/news-w.png' class="w-6 h-6 mx-2 my-auto">
              <% end %>
            </td>
            <td class="px-4 py-1 whitespace-nowrap">
              <%= new.title %>
            </td>
            <td class="px-4 py-1 whitespace-nowrap">
              <%= new.updated_at.day %> <%= I18n.l(new.updated_at, format: "%B")%> <%= new.updated_at.year %>
            </td>
            <td class="px-4 py-1 whitespace-wrap">
              <%= new.content.truncate(64, separator: ' ') %>
            </td>
            <td class="px-4 py-1 whitespace-wrap">
              <%= new.user.name %>
            </td>
            <td class="px-4 py-1 whitespace-wrap">
              <%= editButton("Edit this news", edit_casc_new_path(new.id)) %>
            </td>
            <td class="px-4 py-1 whitespace-wrap">
              <%= delButton("Delete a news", casc_new_path(new), new) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>